[2025-09-06T20:33:17.932+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-09-05T00:00:00+00:00 [queued]>
[2025-09-06T20:33:17.959+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2025-09-05T00:00:00+00:00 [queued]>
[2025-09-06T20:33:17.960+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-09-06T20:33:18.016+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-09-05 00:00:00+00:00
[2025-09-06T20:33:18.035+0000] {standard_task_runner.py:57} INFO - Started process 587 to run task
[2025-09-06T20:33:18.047+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2025-09-05T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpef68llk9']
[2025-09-06T20:33:18.054+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask stream_data_from_api
[2025-09-06T20:33:18.258+0000] {task_command.py:416} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2025-09-05T00:00:00+00:00 [running]> on host 9a4fec9476f6
[2025-09-06T20:33:18.739+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-05T00:00:00+00:00'
[2025-09-06T20:33:19.060+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: connecting to broker:29092 [('172.18.0.9', 29092) IPv4]
[2025-09-06T20:33:19.063+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-09-06T20:33:19.066+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: Connection complete.
[2025-09-06T20:33:19.185+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-09-06T20:33:19.195+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-09-06T20:33:20.078+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: connecting to broker:29092 [('172.18.0.9', 29092) IPv4]
[2025-09-06T20:33:20.094+0000] {conn.py:410} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: Connection complete.
[2025-09-06T20:33:20.105+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.9', 29092)]>: Closing connection. 
[2025-09-06T20:33:37.411+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-06T20:33:37.542+0000] {process_utils.py:131} INFO - Sending 15 to group 587. PIDs of all processes in the group: [587]
[2025-09-06T20:33:37.779+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 587
[2025-09-06T20:33:38.616+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-06T20:33:38.801+0000] {kafka_stream.py:60} ERROR - An error occured: Task received SIGTERM signal
[2025-09-06T20:33:40.639+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.9', 29092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
[2025-09-06T20:33:40.649+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-06T20:33:41.152+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: connecting to broker:29092 [('172.18.0.9', 29092) IPv4]
[2025-09-06T20:33:41.158+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]> returned error 111. Disconnecting.
[2025-09-06T20:33:41.165+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-06T20:33:41.171+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-06T20:33:41.176+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: connecting to broker:29092 [('172.18.0.9', 29092) IPv4]
[2025-09-06T20:33:41.185+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]> returned error 111. Disconnecting.
[2025-09-06T20:33:41.192+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-06T20:33:41.195+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-06T20:33:41.377+0000] {conn.py:380} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: connecting to broker:29092 [('172.18.0.9', 29092) IPv4]
[2025-09-06T20:33:41.385+0000] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]> returned error 111. Disconnecting.
[2025-09-06T20:33:41.388+0000] {conn.py:919} INFO - <BrokerConnection node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.9', 29092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-09-06T20:33:41.401+0000] {client_async.py:331} WARNING - Node 1 connection failed -- refreshing metadata
[2025-09-06T20:33:42.199+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:42.204+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:42.295+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:42.297+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:42.754+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:42.756+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:43.209+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:43.211+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:43.672+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:43.674+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:44.108+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:44.109+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:44.565+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:44.567+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:45.014+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:45.015+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:45.491+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:45.494+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:45.920+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:45.922+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:46.372+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:46.375+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:46.780+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:46.823+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:46.824+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:47.274+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:47.275+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:47.701+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:47.732+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:47.733+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:48.127+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:48.179+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:48.180+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:48.560+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:48.633+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:48.635+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:49.004+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:49.085+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:49.086+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:49.424+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:49.534+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:49.535+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:49.846+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:49.988+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:49.989+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:50.268+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:50.438+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:50.439+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:50.695+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:50.891+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:50.893+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:51.341+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:51.342+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:51.794+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:51.796+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:52.256+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:52.257+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:52.698+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:52.699+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:53.154+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:53.158+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:53.603+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:53.604+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:53.785+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:54.056+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:54.057+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:54.232+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:54.509+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:54.510+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:54.655+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:54.967+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:54.968+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:55.418+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:55.419+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:55.608+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:55.876+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:55.878+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:56.059+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:56.350+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:56.353+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:56.489+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:56.773+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:56.774+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:56.996+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:57.226+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:57.227+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:57.678+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:57.679+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:58.142+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:58.146+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:58.646+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:58.647+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:59.084+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:59.085+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:59.268+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:33:59.538+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:59.539+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:33:59.988+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:33:59.989+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:00.440+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:00.441+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:00.697+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:00.893+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:00.894+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:01.345+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:01.346+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:01.802+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:01.803+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:02.261+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:02.262+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:02.703+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:02.704+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:03.154+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:03.155+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:03.301+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:03.607+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:03.607+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:03.732+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:04.061+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:04.065+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:04.513+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:04.514+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:04.587+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:04.966+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:04.967+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:05.420+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:05.421+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:05.872+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:05.875+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:06.299+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:06.324+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:06.325+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:06.775+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:06.775+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:07.059+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:07.226+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:07.227+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:07.515+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:07.682+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:07.683+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:07.936+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:08.134+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:08.137+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:08.584+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:08.585+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:08.810+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:09.036+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:09.038+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:09.244+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:09.487+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:09.488+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:09.672+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:09.942+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:09.944+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:10.092+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:10.397+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:10.399+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:10.517+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:10.835+0000] {record_accumulator.py:73} WARNING - Produced messages to topic-partition ('users_created', 0) with base offset -1 log start offset None and error None.
[2025-09-06T20:34:10.836+0000] {record_accumulator.py:332} WARNING - Expired 1 batches in accumulator
[2025-09-06T20:34:10.851+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:10.852+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:10.945+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:11.326+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:11.326+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:11.779+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:11.780+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:11.829+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:12.231+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:12.232+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:12.249+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:12.684+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:12.687+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:12.687+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:13.136+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:13.137+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:13.573+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:13.590+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:13.591+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:14.006+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:14.043+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:14.044+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:14.496+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:14.497+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:14.950+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:14.951+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:15.401+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:15.402+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:15.790+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:15.853+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:15.854+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:16.238+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:16.309+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:16.314+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:16.696+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:16.767+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:16.768+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:17.150+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:17.210+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:17.211+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:17.571+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:17.661+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:17.663+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:18.006+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:18.115+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:18.116+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:18.566+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:18.567+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:18.832+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:19.019+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:19.020+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:19.264+0000] {kafka_stream.py:60} ERROR - An error occured: list index out of range
[2025-09-06T20:34:19.477+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:19.478+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:19.923+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:19.924+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:20.376+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:20.377+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:20.828+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:20.829+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:21.280+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:21.280+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:21.731+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:21.732+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:22.183+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:22.184+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:22.635+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:22.637+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:23.088+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:23.089+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:23.549+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:23.550+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:23.994+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:23.995+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:24.446+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:24.446+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:24.901+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:24.903+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:25.406+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:25.407+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:25.803+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:25.805+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:26.254+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:26.255+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:26.707+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:26.708+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:27.158+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:27.159+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:27.610+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:27.611+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:28.148+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:28.150+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:28.522+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:28.523+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:28.969+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:28.969+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:29.422+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:29.423+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:29.873+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:29.873+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:30.326+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:30.328+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:30.780+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:30.781+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:31.230+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:31.230+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:31.682+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:31.683+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:32.135+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:32.136+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:32.600+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:32.601+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:33.038+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:33.038+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:33.499+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:33.499+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:33.942+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:33.944+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:34.394+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:34.395+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:34.849+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:34.849+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:35.300+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:35.302+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:35.752+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:35.754+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:36.206+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:36.207+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:36.656+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:36.657+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:37.152+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:37.156+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:37.562+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:37.563+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:38.056+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-09-06T20:34:38.057+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2025-09-06T20:34:38.062+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=587, name='airflow task ru', status='sleeping', started='20:33:17') did not respond to SIGTERM. Trying SIGKILL
[2025-09-06T20:34:38.065+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 587
[2025-09-06T20:34:38.082+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=587, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='20:33:17') (587) terminated with exit code -9
[2025-09-06T20:34:38.084+0000] {standard_task_runner.py:172} ERROR - Job 11 was killed before it finished (likely due to running out of memory)
